# Generated by Django 4.2.5 on 2023-09-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('passport_details', models.CharField(max_length=100, verbose_name='Паспортные данные')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('passport_details', models.CharField(max_length=100, verbose_name='Паспортные данные')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Вид услуги',
                'verbose_name_plural': 'Виды услуг',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации недвижимости')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площадь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('purchased', models.BooleanField(verbose_name='Актуальность')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.employee', verbose_name='Сотрудник')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.owner', verbose_name='Владелец')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.servicetype', verbose_name='Тип услуги')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.propertytype', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
                'ordering': ['title', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сделки')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.employee', verbose_name='Сотрудник')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.client', verbose_name='Покупатель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.owner', verbose_name='Продавец недвижимости')),
                ('real_estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate', verbose_name='Недвижимость')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.employee'),
        ),
    ]
