# Generated by Django 4.2.5 on 2023-09-06 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'Тип недвижимости', 'verbose_name_plural': 'Типы недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'ordering': ['title', 'price'], 'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Вид услуги', 'verbose_name_plural': 'Виды услуг'},
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_details',
            field=models.CharField(max_length=100, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.client', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.owner', verbose_name='Продавец недвижимости'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='real_estate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate', verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='passport_details',
            field=models.CharField(max_length=100, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='purchased',
            field=models.BooleanField(verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.servicetype', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации недвижимости'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.propertytype', verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Вид'),
        ),
    ]
