# Generated by Django 4.2.5 on 2023-09-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_article_position_promotionalcode_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='photo',
            field=models.ImageField(default='images/default_home.png', upload_to='images', verbose_name='Фото'),
        ),
    ]
