# Generated by Django 4.2.5 on 2023-09-14 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_realestate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации вопроса'),
            preserve_default=False,
        ),
    ]
