# Generated by Django 4.2.5 on 2023-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_comment_promotionalcode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Возраст'),
        ),
    ]
